version: '3.8'

services:
  db:
    image: postgres:13  # PostgreSQL version
    container_name: water_treatment_db
    environment:
      POSTGRES_USER: water_treatment_user
      POSTGRES_PASSWORD: water_treatment_pass
      POSTGRES_DB: water_treatment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: